apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-canary
  name: argo-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-canary
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-canary
    spec:
      containers:
      - image: ghcr.io/diivix/argo-hack:feature-canary
        name: argo-canary
        resources: {}
status: {}